sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t fgiraldolumu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true fgiraldolumu/react-test npm test

after_success:
  - docker build -t fgiraldolumu/multi-client ./client
  - docker build -t fgiraldolumu/multi-nginx ./nginx
  - docker build -t fgiraldolumu/multi-server ./server
  - docker build -t fgiraldolumu/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push fgiraldolumu/multi-client
  - docker push fgiraldolumu/multi-nginx
  - docker push fgiraldolumu/multi-server
  - docker push fgiraldolumu/multi-worker

deploy: 
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket-name: 'elasticbeanstalk-us-east-2-699678850662'
  bucket-path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY